version: "4"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      STRING_SESSION: $STRING_SESSION
      DURATION_LIMIT: $DURATION_LIMIT
      UPSTREAM_REPO: $UPSTREAM_REPO
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
      STRING_SESSION2: $STRING_SESSION2
      STRING_SESSION3: $STRING_SESSION3
      STRING_SESSION4: $STRING_SESSION4
      STRING_SESSION5: $STRING_SESSION5
